# travis-ci.org config for libswish3
#
language: c
script: ./bootstrap && ./configure && make && make testall
install:
 - curl -L https://cpanmin.us | perl - App::cpanminus
 - ~/perl5/bin/cpanm local::lib
 - ~/perl5/bin/cpanm File::Slurper
 - echo '[ $SHLVL -eq 1 ] && eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"' >> ~/.bashrc
