#! /bin/sh

echo "$0 - for initialization of libswish3 build environemnt"
echo "     not needed for user building"


#add --include-deps if you want to bootstrap with any other compiler than gcc
#automake --add-missing --copy --include-deps

set -x

# Mac OS X 10.6 no longer has libtoolize but glibtoolize instead
LIBTOOLIZE=`which libtoolize`
if [ "$LIBTOOLIZE" == "" ]; then
    LIBTOOLIZE=`which glibtoolize`
fi

# aclocal needs these
if [ ! -d m4 ]; then
    mkdir m4
fi
if [ ! -d config ]; then
    mkdir config
fi

aclocal \
 && $LIBTOOLIZE --force --copy \
 && automake --add-missing --include-deps --copy --foreign \
 && autoconf \
 && rm -f config.cache

