#! /bin/sh

echo "$0 - for initialization of libswish3 build environemnt"
echo "     not needed for user building"


#add --include-deps if you want to bootstrap with any other compiler than gcc
#automake --add-missing --copy --include-deps

set -x

if [ ! $SVNDIR ]; then
    SVNDIR=.
fi

# Mac OS X 10.6 no longer has libtoolize but glibtoolize instead
LIBTOOLIZE=`which libtoolize`
if [ ! $LIBTOOLIZE ]; then 
    LIBTOOLIZE=`which glibtoolize`
fi

#echo "libtoolize = $LIBTOOLIZE"

aclocal \
 && $LIBTOOLIZE --force --copy \
 && automake --add-missing --include-deps --copy --foreign \
 && autoconf \
 && rm -f config.cache

