#! /bin/sh

echo "$0 - for initialization of libswish3 build environemnt"
echo "     not needed for user building"


#add --include-deps if you want to bootstrap with any other compiler than gcc
#automake --add-missing --copy --include-deps

set -x

aclocal \
 && libtoolize --force --copy \
 && automake --add-missing --include-deps --copy --foreign \
 && autoconf \
 && rm -f config.cache

