version: 2
jobs:
  build:
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    docker:
      - image: buildpack-deps:latest

    steps:
      - checkout

      - run:
          name: install cpanminus
          command: 'curl -L https://cpanmin.us | perl - App::cpanminus'

      - run:
          name: install perl deps
          command: cpanm File::Slurper Test::More Data::Dump

      - run:
          name: configure locales
          command: 'apt-get update && apt-get install -y locales && locale -a && locale-gen en_US.UTF-8'

      - run:
          name: Build and test
          command: './bootstrap && ./configure && make && (make testall || cat ./src/test-suite.log foo)'
