version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:latest

    steps:
      - checkout

      - run:
          name: install cpanminus
          command: 'curl -L https://cpanmin.us | perl - App::cpanminus'

      - run:
          name: install perl deps
          command: cpanm File::Slurper Test::More Data::Dump

      - run:
          name: Build and test
          command: ./bootstrap && ./configure && make && make testall
