on:
  pull_request:
  push:
    branches:
      - master

name: Build and Test
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        perl: [ '5.34', '5.32', '5.30' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install dependencies
        run: cpanm File::Slurper Test::More Data::Dump
      - name: configure locales
        run: apt-get update && apt-get install -y locales && locale -a && locale-gen en_US.UTF-8
      - name: Build
        run: ./bootstrap && ./configure && make
      - name: Test
        run: make testall || cat ./src/test-suite.log foo
